### ISSUE TITLE
Odd behavior in SPARQL search results  (no idea why)

### ISSUE THREAD

**Issue by fils** [dr-shorthair/GeologicTimeScale#1]
The first two of these queries will work..  the third will not.  However they differ only by the age searched on.  The first 65.  the second 67.  and third 66.  (the third will return no results).

65.
```
prefix gts: <http://resource.geosciml.org/ontology/timescale/gts#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX time: <http://www.w3.org/2006/time#>
SELECT *
WHERE {
               ?era gts:rank ?rank .
               ?era time:hasBeginning/time:inTemporalPosition/time:numericPosition ?begin .
               ?era time:hasEnd/time:inTemporalPosition/time:numericPosition ?end .
               ?era rdfs:label ?name .
               BIND ( "65."^^xsd:decimal AS ?targetAge )
               FILTER ( ?targetAge > xsd:decimal(?end) )
               FILTER ( ?targetAge < xsd:decimal(?begin) )
  
}
```

returns three expected results...

67.
```
prefix gts: <http://resource.geosciml.org/ontology/timescale/gts#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX time: <http://www.w3.org/2006/time#>
SELECT *
WHERE {
               ?era gts:rank ?rank .
               ?era time:hasBeginning/time:inTemporalPosition/time:numericPosition ?begin .
               ?era time:hasEnd/time:inTemporalPosition/time:numericPosition ?end .
               ?era rdfs:label ?name .
               BIND ( "67."^^xsd:decimal AS ?targetAge )
               FILTER ( ?targetAge > xsd:decimal(?end) )
               FILTER ( ?targetAge < xsd:decimal(?begin) )
  
}
```
returns three expected results.

66.
```
prefix gts: <http://resource.geosciml.org/ontology/timescale/gts#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX time: <http://www.w3.org/2006/time#>
SELECT *
WHERE {
               ?era gts:rank ?rank .
               ?era time:hasBeginning/time:inTemporalPosition/time:numericPosition ?begin .
               ?era time:hasEnd/time:inTemporalPosition/time:numericPosition ?end .
               ?era rdfs:label ?name .
               BIND ( "66."^^xsd:decimal AS ?targetAge )
               FILTER ( ?targetAge > xsd:decimal(?end) )
               FILTER ( ?targetAge < xsd:decimal(?begin) )
  
}
```

returns **NO** results.

I am using Blazegraph build version 2.1.1.  I can't tell if this is something to do with my SPARQL engine or something in the RDF.

I would love to know if the third query returns expected results for you, so I can know it's an issue with my engine, not the RDF.

Thanks

**Comment by dr-shorthair** [comment]
I'm using the SPARQL engine built in to TopBraid Composer. 
Result for targetAge 65. - five eras

[era]	rank	begin	end	name	targetAge
isc:Cenozoic	rank:Era	66.0	0.0	Cenozoic Era	65.
isc:Danian	rank:Age	66.0	61.6	Danian Age	65.
isc:Paleocene	rank:Epoch	66.0	56	Paleocene Epoch	65.
isc:Paleogene	rank:Period	66.0	23.03	Paleogene Period	65.
isc:Phanerozoic	rank:Eon	541.0	0.0	Phanerozoic Eon	65.

for 66. - one era

isc:Phanerozoic	rank:Eon	541.0	0.0	Phanerozoic Eon	66.

and for 67. - five eras again

isc:Cretaceous	rank:Period	145.0	66.0	Cretaceous Period	67.
isc:Maastrichtian	rank:Age	72.1	66.0	Maastrichtian Age	67.
isc:Mesozoic	rank:Era	251.902	66.0	Mesozoic Era	67.
isc:Phanerozoic	rank:Eon	541.0	0.0	Phanerozoic Eon	67.
isc:UpperCretaceous	rank:Epoch	100.5	66.0	Upper Cretaceous Epoch	67.

However, I notice that while you cast 66. to xsd:decimal, the data actually has a mixture of xsd:float and time:Number (I could probably do better ...). TopBraid appears to be handling the mixed-type comparisons OK (dunno if the SPARQL spec says anything about this), but looks like Blazegraph doesn't know what to do with time:Number (two of the eras in the first and last have one or other limit where the literal is time:Number, and this includes isc:Phanerozoic which is the single 66. result.

**Comment by dr-shorthair** [comment]
?Looks like Blazegraph doesn't know what to do with literals with type time:Number.

Simon J D Cox
Research Scientist
Land and Water<http://www.csiro.au/Organisation-Structure/Flagships/Land-and-Water>
CSIRO
E simon.cox@csiro.au T +61 3 9545 2365 M +61 403 302 672
   Physical: Reception Central, Bayview Avenue, Clayton, Vic 3168
   Deliveries: Gate 3, Normanby Road, Clayton, Vic 3168
   Postal: Private Bag 10, Clayton South, Vic 3169
people.csiro.au/C/S/Simon-Cox<http://people.csiro.au/C/S/Simon-Cox>
orcid.org/0000-0002-3884-3420<http://orcid.org/0000-0002-3884-3420>
researchgate.net/profile/Simon_Cox3<https://www.researchgate.net/profile/Simon_Cox3>
________________________________

**Comment by fils** [comment]
Simon,
   Ugh..  the twisted world of SPARQL implementations..   not the first time it has caused me pain. 

   I'll update to the latest version (2.1.5) of blazegraph and try that.  If the results are the same I will reference this issue over in the blazegraph repo at https://github.com/blazegraph/database 

  Unless 2.1.5 fixes it though I will likely have to search around for another triple store as I suspect it would take a while for this to propagate through.  I could go back to Virtuoso I guess.

**Comment by fils** [comment]
same exact behavior with 2.1.5 SNAPSHOT

**Comment by fils** [comment]
I think this issue can be closed!

```
prefix gts: <http://resource.geosciml.org/ontology/timescale/gts#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX time: <http://www.w3.org/2006/time#>
SELECT *
WHERE {
               ?era gts:rank ?rank .
               ?era time:hasBeginning/time:inTemporalPosition/time:numericPosition ?begin .
               ?era time:hasEnd/time:inTemporalPosition/time:numericPosition ?end .
               ?era rdfs:label ?name .
               BIND ( "65."^^xsd:decimal AS ?targetAge )
               FILTER ( ?targetAge > xsd:decimal(?end) )
               FILTER ( ?targetAge < xsd:decimal(?begin) )
  
}
```
results in
```
era	rank	begin	end	name	targetAge
<http://resource.geosciml.org/classifier/ics/ischart/Cenozoic>	<http://resource.geosciml.org/ontology/timescale/rank/Era>	66	0	Cenozoic Era	65.
<http://resource.geosciml.org/classifier/ics/ischart/Phanerozoic>	<http://resource.geosciml.org/ontology/timescale/rank/Eon>	541	0	Phanerozoic Eon	65.
<http://resource.geosciml.org/classifier/ics/ischart/Danian>	<http://resource.geosciml.org/ontology/timescale/rank/Age>	66	61.6	Danian Age	65.
<http://resource.geosciml.org/classifier/ics/ischart/Paleocene>	<http://resource.geosciml.org/ontology/timescale/rank/Epoch>	66	56	Paleocene Epoch	65.
<http://resource.geosciml.org/classifier/ics/ischart/Paleogene>	<http://resource.geosciml.org/ontology/timescale/rank/Period>	66	23.03	Paleogene Period	65.
```
and 66.

```
prefix gts: <http://resource.geosciml.org/ontology/timescale/gts#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX time: <http://www.w3.org/2006/time#>
SELECT *
WHERE {
               ?era gts:rank ?rank .
               ?era time:hasBeginning/time:inTemporalPosition/time:numericPosition ?begin .
               ?era time:hasEnd/time:inTemporalPosition/time:numericPosition ?end .
               ?era rdfs:label ?name .
               BIND ( "66."^^xsd:decimal AS ?targetAge )
               FILTER ( ?targetAge > xsd:decimal(?end) )
               FILTER ( ?targetAge < xsd:decimal(?begin) )
  
}
```
results in
```
era	rank	begin	end	name	targetAge
<http://resource.geosciml.org/classifier/ics/ischart/Phanerozoic>	<http://resource.geosciml.org/ontology/timescale/rank/Eon>	541	0	Phanerozoic Eon	66.
```

67. also results in 5 results which I think you said was correct.  


Thanks Simon!

**Comment by dr-shorthair** [comment]
In the dataset all numeric values are encoded as xsd:decimal. 

In OWL-Time proposal is to remove time:Number and replace all uses with xsd:decimal
